const LANGUAGES = { es:'Español', en:'English', fr:'Français', de:'Deutsch', pt:'Português', it:'Italiano', ca:'Català', nl:'Nederlands', pl:'Polski', ru:'Русский', ja:'日本語' };
const state = { items: [], lang: localStorage.getItem('slug-lang') || 'es', theme: localStorage.getItem('slug-theme') || 'system', dirty:false };
const $ = id => document.getElementById(id);
const t = key => state.locale?.[key] || key;
const clone = value => JSON.parse(JSON.stringify(value));

function safeUrl(value, required = true) { if (!value && !required) return ''; try { const url = new URL(value); if (!['http:','https:'].includes(url.protocol)) throw new Error(); return url.href; } catch { throw new Error(t('invalidUrl')); } }
function encodeState() { return btoa(unescape(encodeURIComponent(JSON.stringify(state.items)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function decodeState(hash) { try { const raw = decodeURIComponent(escape(atob(hash.replace(/-/g,'+').replace(/_/g,'/')))); const data = JSON.parse(raw); return Array.isArray(data) ? data : []; } catch { return []; } }
function readHash() { const hash = location.hash.replace(/^#/, ''); if (hash) state.items = decodeState(hash); }
function writeHash() { history.replaceState(null, '', `${location.pathname}${location.search}#${encodeState()}`); }
function markDirty(value=true) { state.dirty=value; document.body.classList.toggle('unsaved',value); $('saveStatus').textContent=value ? t('unsaved') : t('saved'); }
function toast(message) { const node=$('toast'); node.textContent=message; node.classList.add('show'); setTimeout(()=>node.classList.remove('show'),2200); }

async function loadLocale(lang) { try { const response=await fetch(`./locales/${lang}.json`); if (!response.ok) throw Error(); state.locale=await response.json(); } catch { if (lang !== 'en') return loadLocale('en'); state.locale={}; } document.documentElement.lang=lang; applyTranslations(); }
function applyTranslations() { document.title=t('title'); const map={emptyTitle:'emptyTitle',emptyBody:'emptyBody',menuTitle:'menu',addAppButton:'addApp',addFolderButton:'addFolder',exportButton:'exportUrl',importButton:'importUrl',themeLabel:'theme',languageLabel:'language',footerText:'footer',searchTitle:'search',nameLabel:'name',urlLabel:'url',iconLabel:'icon',saveButton:'save',cancelButton:'cancel'}; Object.entries(map).forEach(([id,key])=>{if($(id)) $(id).textContent=t(key)}); $('searchInput').placeholder=t('searchPlaceholder'); $('saveStatus').textContent=state.dirty?t('unsaved'):t('saved'); }
function render() { const grid=$('launcherGrid'); grid.replaceChildren(); $('emptyState').hidden=state.items.length>0; const fragment=document.createDocumentFragment(); state.items.forEach(item=>{ const el=document.createElement(item.type==='app'?'a':'button'); el.className='app-card'; el.dataset.id=item.id; el.type='button'; if(item.type==='app'){el.href=item.url;el.target='_blank';el.rel='noopener noreferrer';} else el.setAttribute('aria-label',`${item.name}: ${item.children?.length||0}`); if(item.type==='app'){const img=document.createElement('img');img.loading='lazy';img.decoding='async';img.src=item.icon||`https://www.google.com/s2/favicons?domain=${encodeURIComponent(new URL(item.url).hostname)}&sz=128`;img.alt='';el.append(img);} else {const folder=document.createElement('span');folder.className='folder-icon';folder.setAttribute('aria-hidden','true');folder.textContent='▣';el.append(folder);} const label=document.createElement('span');label.textContent=item.name;el.append(label); fragment.append(el);}); grid.append(fragment); }
function openEditor(item=null) { $('editorForm').reset(); $('editId').value=item?.id||''; $('nameInput').value=item?.name||''; $('urlInput').value=item?.url||''; $('iconInput').value=item?.icon||''; $('editorTitle').textContent=item?t('editApp'):t('addApp'); $('editorDialog').showModal(); $('nameInput').focus(); }
function addApp() { openEditor(); }
function saveApp(event) { event.preventDefault(); try { const name=$('nameInput').value.trim(); if(!name) throw Error(t('invalidName')); const url=safeUrl($('urlInput').value); const icon=safeUrl($('iconInput').value,false); const id=$('editId').value||crypto.randomUUID(); const old=state.items.find(x=>x.id===id); if(old) Object.assign(old,{name,url,icon}); else state.items.push({id,type:'app',name,url,icon}); $('editorDialog').close(); markDirty(); render(); } catch(error) { toast(error.message); } }
function addFolder() { $('folderForm').reset(); $('folderDialog').showModal(); $('folderNameInput').focus(); }
function saveFolder(event) { event.preventDefault(); const name=$('folderNameInput').value.trim(); if(!name) return toast(t('invalidName')); state.items.push({id:crypto.randomUUID(),type:'folder',name,children:[]}); $('folderDialog').close(); markDirty(); render(); }
function openPanel(open=true) { $('sidePanel').classList.toggle('open',open); $('sidePanel').ariaHidden=String(!open); $('sidePanel').toggleAttribute('inert',!open); $('panelBackdrop').hidden=!open; $('menuButton').ariaExpanded=String(open); if(open) $('closeMenuButton').focus(); else $('menuButton').focus(); }
function exportConfig() { writeHash(); markDirty(false); navigator.clipboard?.writeText(location.href).then(()=>toast(t('urlCopied'))).catch(()=>toast(location.href)); }
async function importConfig() { const value=prompt(t('pasteUrl')); if(!value) return; try { const url=new URL(value); state.items=decodeState(url.hash.slice(1)); markDirty(); render(); } catch { toast(t('invalidUrl')); } }
function search() { $('searchDialog').showModal(); $('searchInput').focus(); renderSearch(''); }
function renderSearch(query) { const list=$('searchResults'); list.replaceChildren(); const matches=state.items.filter(x=>x.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())); matches.forEach(item=>{const button=document.createElement('button');button.className='search-result';button.type='button';button.textContent=item.name;button.addEventListener('click',()=>{if(item.type==='app') window.open(item.url,'_blank','noopener,noreferrer');$('searchDialog').close();});list.append(button);}); }
function setTheme(theme) { state.theme=theme; localStorage.setItem('slug-theme',theme); const actual=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme; document.body.dataset.theme=actual; }

$('editorForm').addEventListener('submit',saveApp); $('folderForm').addEventListener('submit',saveFolder); $('addAppButton').addEventListener('click',()=>{openPanel(false);addApp()}); $('emptyAddButton').addEventListener('click',addApp); $('addFolderButton').addEventListener('click',()=>{openPanel(false);addFolder()}); $('menuButton').addEventListener('click',()=>openPanel(true)); $('closeMenuButton').addEventListener('click',()=>openPanel(false)); $('panelBackdrop').addEventListener('click',()=>openPanel(false)); $('searchButton').addEventListener('click',search); $('brandButton').addEventListener('click',()=>toast('SlugLauncher')); $('exportButton').addEventListener('click',()=>{openPanel(false);exportConfig()}); $('importButton').addEventListener('click',()=>{openPanel(false);importConfig()}); $('themeSelect').addEventListener('change',e=>setTheme(e.target.value)); $('languageSelect').addEventListener('change',async e=>{state.lang=e.target.value;localStorage.setItem('slug-lang',state.lang);await loadLocale(state.lang);render();}); $('searchInput').addEventListener('input',e=>renderSearch(e.target.value)); $('cancelButton').addEventListener('click',()=>$('editorDialog').close()); document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.closeDialog).close()));
$('launcherGrid').addEventListener('contextmenu',event=>{const card=event.target.closest('.app-card'); if(!card) return; event.preventDefault(); const item=state.items.find(x=>x.id===card.dataset.id); if(item?.type==='app') openEditor(item);});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.theme==='system')setTheme('system')});
for(const [code,label] of Object.entries(LANGUAGES)){const option=new Option(label,code);$('languageSelect').add(option);} $('languageSelect').value=state.lang; $('themeSelect').value=state.theme; readHash(); setTheme(state.theme); loadLocale(state.lang).then(render); markDirty(false);
